{
    "status": "created",
    "documentsUri": "/envelopes/9b83f2aa-c878-4525-adae-acfdf931b6f3/documents",
    "recipientsUri": "/envelopes/9b83f2aa-c878-4525-adae-acfdf931b6f3/recipients",
    "envelopeUri": "/envelopes/9b83f2aa-c878-4525-adae-acfdf931b6f3",
    "emailSubject": "Test Email Subecjt",
    "emailBlurb": "Email body",
    "envelopeId": "9b83f2aa-c878-4525-adae-acfdf931b6f3",
    "customFieldsUri": "/envelopes/9b83f2aa-c878-4525-adae-acfdf931b6f3/custom_fields",
    "notificationUri": "/envelopes/9b83f2aa-c878-4525-adae-acfdf931b6f3/notification",
    "enableWetSign": "true",
    "createdDateTime": "2013-09-04T18:26:10.9300000",
    "statusChangedDateTime": "2013-09-04T18:26:10.9300000",
    "documentsCombinedUri": "/envelopes/9b83f2aa-c878-4525-adae-acfdf931b6f3/documents/combined",
    "certificateUri": "/envelopes/9b83f2aa-c878-4525-adae-acfdf931b6f3/documents/certificate",
    "templatesUri": "/envelopes/9b83f2aa-c878-4525-adae-acfdf931b6f3/templates"
}