{
  "resultSetSize": "2",
  "totalSetSize": "2",
  "startPosition": "0",
  "endPosition": "9",
  "nextUri": "https://www.docusign.net/restapi/v2/accounts/testaccountid/envelopes1",
  "previousUri": "",
  "envelopes": [
  {
      "status": "sent",
      "documentsUri": "/envelopes/11111111-2222-3333-4444-envelope0000/documents",
      "recipientsUri": "/envelopes/11111111-2222-3333-4444-envelope0000/recipients",
      "envelopeUri": "/envelopes/11111111-2222-3333-4444-envelope0000",
      "envelopeId": "11111111-2222-3333-4444-envelope0000",
      "customFieldsUri": "/envelopes/11111111-2222-3333-4444-envelope0000/custom_fields",
      "notificationUri": "/envelopes/11111111-2222-3333-4444-envelope0000/notification",
      "statusChangedDateTime": "2013-10-14T16:13:00.1330000",
      "documentsCombinedUri": "/envelopes/11111111-2222-3333-4444-envelope0000/documents/combined",
      "certificateUri": "/envelopes/11111111-2222-3333-4444-envelope0000/documents/certificate",
      "templatesUri": "/envelopes/11111111-2222-3333-4444-envelope0000/templates"
    },
    {
      "status": "completed",
      "documentsUri": "/envelopes/11111111-2222-3333-4444-envelope0009/documents",
      "recipientsUri": "/envelopes/11111111-2222-3333-4444-envelope0009/recipients",
      "envelopeUri": "/envelopes/11111111-2222-3333-4444-envelope0009",
      "envelopeId": "11111111-2222-3333-4444-envelope0009",
      "customFieldsUri": "/envelopes/11111111-2222-3333-4444-envelope0009/custom_fields",
      "notificationUri": "/envelopes/11111111-2222-3333-4444-envelope0009/notification",
      "statusChangedDateTime": "2013-10-14T16:13:00.1330000",
      "documentsCombinedUri": "/envelopes/11111111-2222-3333-4444-envelope0009/documents/combined",
      "certificateUri": "/envelopes/11111111-2222-3333-4444-envelope0009/documents/certificate",
      "templatesUri": "/envelopes/11111111-2222-3333-4444-envelope0009/templates"
    }
  ]
}
