/* Achievement Scores */
.achievementScores {
    font-size: 36px;
    color: #2C7F5C;
    letter-spacing: 0;
    font-weight: 600;
  }
  
.nextBadgeLevel {
    color: #2C7F5C;
    font-weight: 600;
}
  
/* Badge Labels and Achievement Labels */
.badgeLabels {
    font-size: 16px;
    letter-spacing: 0;
    line-height: 20px;
    font-weight: 300;
}

.actionButtons > .slds-button+.slds-button{
    margin-left: 25px;
}