/*************************************************************************     
* @description This class is used to set parser name,request version,payload and response 
* @param NA
* @Author InfoSys Developer
**************************************************************************/
public class EtlItem {
/**
* @description parserName
*/
public String parserName {get; set;}
 /**
 * @description requestVersion
 */
public String requestVersion {get; set;}
/**
 * @description payload
 */    
public String payload {get; set;}
/**
 * @description response
 */ 
public String response {get; set;}
}